on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Run tests

jobs:

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests with Tox
        uses: fedora-python/tox-github-action@master
        with:
          tox_env: py
          dnf_install: krb5-devel libpq-devel
